configuration:
  inference:
    providers:
      anthropic:
        enabled: true
        apikey: "<your_anthropic_api_key>"
  tools:
    providers:
      mcp:
        enabled: true
        servers:
          - name: atlassian
            description: "MCP server allowing access to Jira and Confluence."
            url: "https://mcp.atlassian.com/v1/mcp/preview"
            credentials:
              basic:
                username: "<Username>"
                password: "<API Token>"
    configuration:
      js_bitbucket_pr:
        api_key: "<your_bitbucket_api_key>"
      git:
        repositories:
          - url: "^ssh://git@bitbucket.org:example/.*$"
            email: "beaver@example.com"
            display_name: "Beaver Bot"
            ssh_key: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              <your_ssh_private_key>
              -----END OPENSSH PRIVATE KEY-----
            known_hosts:
              - "bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQeJzhupRu0u0cdegZIa8e86EG2qOCsIsD1Xw0xSeiPDlCr7kq97NLmMbpKTX6Esc30NuoqEEHCuc7yWtwp8dI76EEEB1VqY9QJq6vk+aySyboD5QF61I/1WeTwu+deCbgKMGbUijeXhtfbxSxm6JwGrXrhBdofTsbKRUsrN1WoNgUa8uqN1Vx6WAJw1JHPhglEGGHea6QICwJOAr/6mrui/oB7pkaWKHj3z7d1IC4KWLtY47elvjbaTlkN04Kc/5LFEirorGYVbt15kAUlqGM65pk6ZBxtaO3+30LVlORZkxOh+LKL/BvbZ/iRNhItLqNyieoQj/uh/7Iv4uyH/cV/0b4WDSd3DptigWq84lJubb9t/DnZlrJazxyDCulTmKdOR7vs9gMTo+uoIrPSb8ScTtvw65+odKAlBj59dhnVp9zd7QUojOpXlL62Aw56U4oO+FALuevvMjiWeavKhJqlR7i5n9srYcrNV7ttmDw7kf/97P5zauIhxcjX+xHv4M="
              - "bitbucket.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPIQmuzMBuKdWeF4+a2sjSSpBK0iqitSQ+5BM9KhpexuGt20JpTVM7u5BDZngncgrqDMbWdxMWWOGtZ9UgbqgZE="
              - "bitbucket.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO"
agents:
  reviewer:
    metadata:
      name: reviewer
      display_name: Reviewer
      description: The reviewer reviews pull requests and provides feedback.
    inference:
      model: claude-fable-5
    tools:
      permissions:
        - name: js_bitbucket_pr_comment
        - name: js_bitbucket_pr_diff
        - name: js_bitbucket_pr_get
    prompt: |
      Your task is to review pull requests and provide feedback.

webhooks:
  pr_review:
    metadata:
      name: pr_review
      display_name: PR Review
      description: This webhook triggers a PR review process when a pull request is created or updated.
      token: "REPLACE_WITH_YOUR_WEBHOOK_TOKEN"
    handler:
      agent: reviewer
      prompt: |
        Hi Reviewer,

        A new Bitbucket pull request has been created. Please review the changes and provide your feedback as comments and tasks on the pull request.

        Always check other comments first to avoid duplicating feedback. If you find any issues, provide clear and actionable feedback.

        Workspace: {{ Body.repository.workspace.slug }}
        Repository: {{ Body.repository.name }}
        Pull request id: {{ Body.pullrequest.id }}

        Title: {{ Body.pullrequest.rendered.title.raw }}
        Description:
        {{ Body.pullrequest.rendered.description.raw | indent(prefix="  ") }}
