apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.name" . }}-webhook
  labels: {{ include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.name" . }}-webhook
  minReplicas: {{ .Values.webhook.hpa.minReplicas }}
  maxReplicas: {{ .Values.webhook.hpa.maxReplicas }}
  metrics: {{ toYaml .Values.webhook.hpa.metrics | nindent 4 }}
