apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-configuration
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  configuration.yaml: |
    {{- tpl (toYaml .Values.configuration) $ | nindent 4 }}
