apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-agents
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $name, $content := .Values.agents }}
  {{ $name }}.yaml: |
    metadata: {{- tpl (toYaml $content.metadata) $ | nindent 6 }}
    permissions: {{- tpl (toYaml $content.permissions) $ | nindent 6 }}
  {{ $name }}.md: |
    {{- tpl $content.prompt $ | nindent 6 }}
{{- end }}
