apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-agents
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $name, $content := .Values.agents }}
  {{ $name }}.yaml: |
    {{- toYaml $content | nindent 4 }}
{{- end }}
