[package]
name = "app-adapters"
version.workspace = true
edition.workspace = true

[dependencies]
app-domains.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
tokio.workspace = true
async-trait.workspace = true
regex.workspace = true
http.workspace = true
base64.workspace = true
chrono.workspace = true

genai = "0.7.0-beta.19"
config = "0.15.23"
tera = "2.0.0"
boa_engine = "0.21.1"
boa_runtime = "0.21.1"
boa_gc = "0.21.1"
rmcp = { version = "3.1.2", features = [
  "client",
  "transport-streamable-http-client-reqwest",
  "auth",
] }
walkdir = "2.5.0"
git2 = { version = "0.21.0", features = ["https", "ssh", "vendored-libgit2", "vendored-openssl"] }
ssh2 = { version = "0.9.6", features = ["vendored-openssl"] }
