[package]
name = "app-adapters"
version.workspace = true
edition.workspace = true

[dependencies]
app-domains.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
tokio.workspace = true
async-trait.workspace = true
regex.workspace = true
http.workspace = true
base64.workspace = true

genai = "0.7.0-beta.9"
config = "0.15.23"
tera = "2.0.0"
boa_engine = "0.21.1"
boa_runtime = "0.21.1"
boa_gc = "0.21.1"
