apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-webhooks
  labels: {{ include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.webhooks }}
  {{ $name }}.yaml: |
    {{- toYaml $content | nindent 4 }}
  {{- end }}
